### ISSUE TITLE
Missing /etc/s6/skel

### ISSUE THREAD

**Issue by jspc** [dslm4515/MLFS-S6-Bootscripts#8]
The README suggests that the `s6/` directory should include `skel`, which (after copy to `/etc`) is then used as input to `-f skeldir` when calling `s6-linux-init-maker`.

This directory doesn't exist in the repo. Is this by mistake? Or do I need to generate it?

Thanks!

**Comment by dslm4515** [comment]
Yes the skel directory is needed. I forgot to add it to the repo from my test build environment.
